services:
  train-sft :
    build:
      context: .
      dockerfile: Dockerfile  # .train - for gemma4
    image: nas-rlm-train:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - .:/app
      - ./hf_cache:/root/.cache/huggingface
    environment:
      SFT_MODEL_PATH: /app/weights/qwen_gsm8k_sft_lora
      HF_HOME: /root/.cache/huggingface
    working_dir: /app
    command: ["python3", "-m", "src.rlm.train_sft"]

  train-grpo:
    build:
      context: .
      dockerfile: Dockerfile  # .train - for gemma4
    image: nas-rlm-train:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - .:/app
      - ./hf_cache:/root/.cache/huggingface
    environment:
      SFT_MODEL_PATH: /app/weights/qwen_gsm8k_sft_lora
      FINAL_MODEL_PATH: /app/weights/qwen_gsm8k_grpo_lora
      HF_HOME: /root/.cache/huggingface
    working_dir: /app
    command: ["python3", "-m", "src.rlm.train_grpo"]

  agent-inference:
    build:
      context: .
      dockerfile: Dockerfile
    image: nas-rlm-app:latest
    ports:
      - "8010:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - .:/app
      - ./hf_cache:/root/.cache/huggingface
    environment:
      SFT_MODEL_PATH: /app/weights/qwen_gsm8k_sft_lora
      FINAL_MODEL_PATH: /app/weights/qwen_gsm8k_grpo_lora
      HF_HOME: /root/.cache/huggingface
    working_dir: /app
    command: ["python3", "-m", "src.api.app"]

  agent-bash:
    build:
      context: .
      dockerfile: Dockerfile
    image: nas-rlm-app:latest
    stdin_open: true  # for interactive bash
    tty: true         # for interactive bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - .:/app
      - ./hf_cache:/root/.cache/huggingface
    environment:
      SFT_MODEL_PATH: /app/weights/qwen_gsm8k_sft_lora
      FINAL_MODEL_PATH: /app/weights/qwen_gsm8k_grpo_lora
      HF_HOME: /root/.cache/huggingface
    working_dir: /app
    command: ["bash"]